title: "Cris"
description: "PhD student slash researcher slash tech leader slash traveler slash cat lady"
baseurl: "/cristiane"
permalink: "/stories/:year/:month/:day/:title/"
url: ""

email: "cristiane@example.com"

social:
  - label: "LinkedIn"
    url: "https://www.linkedin.com/in/souzacris/"
  - label: "Google Scholar"
    url: "https://scholar.google.com/citations?user=Zeajh2IAAAAJ&hl=en"
  - label: "GitHub"
    url: "https://github.com/souza-cris"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "story"

exclude:
  - Gemfile
  - Gemfile.lock
  - specs
  - .specify
  - .claude
  - CLAUDE.md
